import { ACTIONS, PolicySchema, type Policy } from "@/lib/schemas/policy";

const injectionRules = ACTIONS.map((action, index) => ({
  id: `deny-prompt-injection-${action}`,
  priority: 10 + index,
  action,
  decision: "DENY" as const,
  all: [
    {
      field: "contains_prompt_injection" as const,
      operator: "eq" as const,
      value: true,
    },
  ],
  any: [],
  reason: "Policy bypass, hiding, or override attempt detected.",
  sourceSopLines: [11],
}));

export const defaultPolicy: Policy = PolicySchema.parse({
  id: "policygate-demo-policy",
  name: "PolicyGate Demo Policy",
  version: "1.0.0",
  defaultDecision: "DENY",
  rules: [
    ...injectionRules,
    {
      id: "deny-repeat-refund-count-abuse",
      priority: 100,
      action: "refund_order",
      decision: "DENY",
      all: [{ field: "refund_count_30d", operator: "gte", value: 5 }],
      any: [],
      reason: "Customer has 5 or more refund requests in the last 30 days.",
      sourceSopLines: [5],
    },
    {
      id: "deny-repeat-refund-amount-abuse",
      priority: 110,
      action: "refund_order",
      decision: "DENY",
      all: [{ field: "refund_amount_30d", operator: "gt", value: 200 }],
      any: [],
      reason: "Customer has more than $200 refunded in the last 30 days.",
      sourceSopLines: [6],
    },
    {
      id: "deny-same-address-refund-abuse",
      priority: 120,
      action: "refund_order",
      decision: "DENY",
      all: [
        { field: "same_address_refund_count_30d", operator: "gte", value: 10 },
      ],
      any: [],
      reason: "Shipping address has 10 or more refund requests in the last 30 days.",
      sourceSopLines: [7],
    },
    {
      id: "deny-refund-over-200",
      priority: 130,
      action: "refund_order",
      decision: "DENY",
      all: [{ field: "amount", operator: "gt", value: 200 }],
      any: [],
      reason: "Refund amount is above $200.",
      sourceSopLines: [4],
    },
    {
      id: "allow-low-risk-refund-up-to-50",
      priority: 140,
      action: "refund_order",
      decision: "ALLOW",
      all: [
        { field: "amount", operator: "lte", value: 50 },
        { field: "risk_level", operator: "eq", value: "LOW" },
      ],
      any: [],
      reason: "Refund amount is up to and including $50 and risk is LOW.",
      sourceSopLines: [1],
    },
    {
      id: "approve-medium-risk-refund-up-to-50",
      priority: 150,
      action: "refund_order",
      decision: "APPROVAL",
      all: [
        { field: "amount", operator: "lte", value: 50 },
        { field: "risk_level", operator: "eq", value: "MEDIUM" },
      ],
      any: [],
      reason: "Small refund, but risk signals require human approval.",
      sourceSopLines: [2],
    },
    {
      id: "approve-high-risk-refund-up-to-50",
      priority: 160,
      action: "refund_order",
      decision: "APPROVAL",
      all: [
        { field: "amount", operator: "lte", value: 50 },
        { field: "risk_level", operator: "eq", value: "HIGH" },
      ],
      any: [],
      reason: "Small refund, but HIGH risk requires human approval.",
      sourceSopLines: [2],
    },
    {
      id: "approve-refund-over-50-up-to-200",
      priority: 170,
      action: "refund_order",
      decision: "APPROVAL",
      all: [
        { field: "amount", operator: "gt", value: 50 },
        { field: "amount", operator: "lte", value: 200 },
      ],
      any: [],
      reason: "Refund amount is above $50 and up to and including $200.",
      sourceSopLines: [3],
    },
    {
      id: "deny-export-customer-data",
      priority: 180,
      action: "export_customer_data",
      decision: "DENY",
      all: [
        {
          field: "customer_data_type",
          operator: "in",
          value: ["email", "address", "phone", "personal_data"],
        },
      ],
      any: [],
      reason: "Exporting customer emails, addresses, phone numbers, or personal data is forbidden.",
      sourceSopLines: [8],
    },
    {
      id: "deny-modify-policy",
      priority: 190,
      action: "modify_policy",
      decision: "DENY",
      all: [],
      any: [],
      reason: "Modifying permission rules is forbidden.",
      sourceSopLines: [9],
    },
    {
      id: "deny-bulk-refund",
      priority: 200,
      action: "bulk_refund",
      decision: "DENY",
      all: [],
      any: [],
      reason: "Bulk refunds are forbidden.",
      sourceSopLines: [10],
    },
  ],
});
